<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('200', '/uploads/220408/1-22040Q503515E.png');
$maNum = 1;
$myaddons[$maNum] = array('201', '/uploads/allimg/220408/1-22040Q5044QS.png');
$maNum = 2;
$myaddons[$maNum] = array('202', '/uploads/allimg/220408/1-22040Q50542929.png');
$maNum = 3;
$myaddons[$maNum] = array('203', '/uploads/allimg/220408/1-22040Q5060K05.png');
$maNum = 4;
