<a href="[field:typelink/]">load more</a></div>
      <div class="c"></div>
      <div class="news-more">{dede:type typeid='10'}<a href="[field:typelink/]">load more</a></div>
      
    </div>
  </div>
  <div class="row4 fix">
    <div class="wp">
      <div class="tit-i">
        <h3>联系我们</h3>
        <h5><span>contact</span> Maker Cloud</h5>
      </div>
      <div class="contact-l">
        <ul class="ul-contact">
          <li class="li1">深圳市南山区幸福大道万达广场88-34</li>
          <li class="li2"><a href="tel:1532568999">15325329999 (咨询) / <a href="tel:023-63695689">023-63695689 (售后)<br />
            <a href="tel:0315 855 8855">0315 855 8855 (咨询)</a></li>
          <li class="li3"><a href="mailto:329435596@qq.com">88889999@qq.com</a></li>
        </ul>
      </div>
      <div class="contact-r">
        <form action="/plus/diy.php" class="contact-form" enctype="multipart/form-data" method="post">
          <input type="hidden" name="action" value="post" />
          <input type="hidden" name="diyid" value="1" />
          <input type="hidden" name="do" value="2" />
          <div class="">
            <input type="text" class="inp l" name="name" id="name" placeholder="您的姓名">
            <input type="text" class="inp r" name="tel" id="tel" placeholder="您的联系方式">
          </div>
          <textarea cols="30" rows="10" name="nr" id="nr"></textarea>
          <input type="hidden" name="dede_fields" value="name,text;tel,text;nr,text" />
          <input type="hidden" name="dede_fieldshash" value="1150bc325e255641e2db4115e8c9c51f" />
          <input type="submit" value="提交您的需求" class="sub" id="sub">
        </form>
      </div>
    </div>
  </div>
  <div class="map">
    <div class="map-s"> <a href="javascript:void(0);" class="btn"><em></em>点击展开地图</a> </div>
    <div class="map-pop"> <a href="javascript:void(0);" class="btn-down"></a>
      <div class="map-bg1"></div>
      <div class="map-bg2"></div>
      <div id="map" class="map-i" style="width:100%; height: 100%;"> </div>
    </div>
  </div>
</div>
<!-- end #bd -->
<div class="c"></div>
<!-- begin #fd --> 
{dede:include filename="footer.htm"