<div style="padding:20; margin:0;  width:216px; height:155px;"><img src="/skin/images/k1.png" /></div></td>
            <td><div style="padding:20; margin-top:70px;margin-left:35px;  width:65px; height:155px;"><img src="/skin/images/article_next.png" /></div></td>
            <td><div style="padding:20; margin:0;  width:216px; height:155px;"><img src="/skin/images/k2.png" /></div></td>
            <td><div style="padding:20; margin-top:70px;margin-left:35px;  width:65px; height:155px;"><img src="/skin/images/article_next.png" /></div></td>
            <td><div style="padding:20; margin:0;  width:216px; height:155px;"><img src="/skin/images/k3.png" /></div></td>
            <td><div style="padding:20;  margin-top:70px;margin-left:35px;  width:65px; height:155px;"><img src="/skin/images/article_next.png" /></div></td>
            <td><div style="padding:20; margin:0;  width:216px; height:155px;"><img src="/skin/images/k4.png" /></div></td>
          
          </tr></table>
          <table><tr>
            <td><div style="padding:20; margin:0;  width:216px; height:155px;"><img src="/skin/images/k5.png" /></div></td>
            <td><div style="padding:20; margin-top:70px;margin-left:35px;  width:65px; height:155px;"><img src="/skin/images/article_next.png" /></div></td>
            <td><div style="padding:20; margin:0;  width:216px; height:155px;"><img src="/skin/images/k6.png" /></div></td>
            <td><div style="padding:20; margin-top:70px;margin-left:35px;  width:65px; height:155px;"><img src="/skin/images/article_next.png" /></div></td>
            <td><div style="padding:20; margin:0;  width:216px; height:155px;"><img src="/skin/images/k7.png" /></div></td>
            <td><div style="padding:20;  margin-top:70px;margin-left:35px;  width:65px; height:155px;"><img src="/skin/images/article_next.png" /></div></td>
            <td><div style="padding:20; margin:0;  width:216px; height:155px;"><img src="/skin/images/k8.png" /></div></td>
          
          </tr></table>
    
        </div>

      
        <div class="c"></div>
        <div class="news-more">{dede:type typeid='1'}<a href="[field:typelink/]">load more</a>