<?php
$z[0]=Array("channel","\r\n        <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n        ",184,423);
$z[0][4]['type']="top";
$z[0][4]['row']="10";
$z[0][4]['currentstyle']="<li><a href='~typelink~' ~rel~ class='mycur'><span>~typename~</span></a></li>";
$z[1]=Array("channel","\r\n    <li><a href='[field:typeurl/]' class=\"v1\">[field:typename/]</a></li>\r\n    ",763,994);
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[1][4]['currentstyle']="<li><a href='~typelink~' ~rel~ class='v1'><span>~typename~</span></a></li>";

?>