<?php
$z[0]=Array("global","",64,90);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",134,164);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",201,228);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",789,824);
$z[3][4]['filename']="head.htm";
$z[4]=Array("type","<a href=\"[field:typelink/]\"></a>",4940,5006);
$z[4][4]['typeid']="1";
$z[5]=Array("type","<a href=\"[field:typelink/]\">load more</a>",7846,7921);
$z[5][4]['typeid']="2";
$z[6]=Array("type","<a href=\"[field:typelink/]\">load more</a>",7960,8035);
$z[6][4]['typeid']="3";
$z[7]=Array("include","",10076,10113);
$z[7][4]['filename']="footer.htm";

?>